use axum::{
    extract::{
        ws::{Message, WebSocket, WebSocketUpgrade},
        State,
    },
    response::IntoResponse,
};
use futures::{sink::SinkExt, stream::StreamExt};
use std::sync::Arc;
use tokio::sync::RwLock;
use chrono::Utc;
use uuid::Uuid;

use crate::models::{self, MessageRole, ToolActivity, ToolType, WsMessage};
use crate::AppState;

/// WebSocket upgrade handler
pub async fn websocket_handler(
    ws: WebSocketUpgrade,
    State(state): State<Arc<RwLock<AppState>>>,
) -> impl IntoResponse {
    ws.on_upgrade(move |socket| handle_socket(socket, state))
}

/// Handle individual WebSocket connection
async fn handle_socket(socket: WebSocket, state: Arc<RwLock<AppState>>) {
    let (mut sender, mut receiver) = socket.split();

    tracing::info!("New WebSocket connection established");

    while let Some(msg) = receiver.next().await {
        if let Ok(msg) = msg {
            match msg {
                Message::Text(text) => {
                    if let Ok(ws_msg) = serde_json::from_str::<WsMessage>(&text) {
                        match ws_msg {
                            WsMessage::Chat { project_id, content } => {
                                tracing::info!("Received chat message: {}", content);
                                
                                // Process the message and generate response
                                let response = process_chat_message(&state, &project_id, &content).await;
                                
                                // Send tool activity updates
                                if let Some(activities) = &response.tool_activity {
                                    for activity in activities {
                                        let activity_msg = WsMessage::ToolActivity {
                                            activity: activity.clone(),
                                        };
                                        if let Ok(json) = serde_json::to_string(&activity_msg) {
                                            let _ = sender.send(Message::Text(json)).await;
                                        }
                                    }
                                }
                                
                                // Send chat response
                                let response_msg = WsMessage::ChatResponse { message: response };
                                if let Ok(json) = serde_json::to_string(&response_msg) {
                                    let _ = sender.send(Message::Text(json)).await;
                                }
                            }
                            _ => {}
                        }
                    }
                }
                Message::Close(_) => {
                    tracing::info!("WebSocket connection closed");
                    break;
                }
                _ => {}
            }
        }
    }
}

/// Process chat message and generate response
async fn process_chat_message(
    _state: &Arc<RwLock<AppState>>,
    _project_id: &str,
    content: &str,
) -> models::Message {
    // For now, return a mock response
    // In production, this would call the Python agent service
    
    let tool_activities = vec![
        ToolActivity {
            activity_type: ToolType::Search,
            description: "Searched workspace for relevant content".to_string(),
            file_path: None,
            timestamp: Utc::now(),
        },
        ToolActivity {
            activity_type: ToolType::Read,
            description: "Read auth/strategy.md".to_string(),
            file_path: Some("auth/strategy.md".to_string()),
            timestamp: Utc::now(),
        },
    ];

    models::Message {
        id: Uuid::new_v4().to_string(),
        role: MessageRole::Assistant,
        content: format!(
            "I've analyzed your request about '{}'. Based on my search of the workspace, here's what I found...\n\nThis is a simulated response. In production, this would be generated by the Ollama Gemma model.",
            content
        ),
        timestamp: Utc::now(),
        tool_activity: Some(tool_activities),
    }
}
